// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DealerOn.SalesTax.Domain.Sqlite.Migrations
{
    [DbContext(typeof(SalesTaxDbContext))]
    [Migration("20240906015207_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ClassifierDefinitionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TraitType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TraitValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClassifierDefinitions");
                });

            modelBuilder.Entity("TaxConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ImportDutyRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalesTaxRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaxConfigs");
                });

            modelBuilder.Entity("TaxExemptCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaxConfigEntityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaxConfigEntityId");

                    b.ToTable("TaxExemptCategories");
                });

            modelBuilder.Entity("TaxExemptCategoryEntity", b =>
                {
                    b.HasOne("TaxConfigEntity", null)
                        .WithMany("ExemptCategories")
                        .HasForeignKey("TaxConfigEntityId");
                });

            modelBuilder.Entity("TaxConfigEntity", b =>
                {
                    b.Navigation("ExemptCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
